### ISSUE TITLE
Search parameter not appended in URL when there are no results

### ISSUE THREAD

**Issue by suprishi** [devonfw/architectures#56]
### Expected behavior

As a visitor of the architecture browser, I expect the search parameter to be appended to the URL every time I perform a search.

### Actual behavior
Search parameter is not appended to the URL when there are no results to show.
![image](https://user-images.githubusercontent.com/28841459/134625054-fbb06d3d-c73f-4831-8775-91f4ba407e60.png)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Visit the architecture browser  at https://devonfw.com/website/pages/architectures/
2. Search for "auth"

**Comment by tobka777** [comment]
I add query parameter on change to url. Locally the parameter does not refresh if I remove a character. Maybe we have to fix the event listeners.
