### ISSUE TITLE
Only show finished solutions

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/architectures#64]
As devonfw team, I want the user only to see finished solutions so that the architecture browser makes a good first impression.

There should be a parameter to activate/show the "Maturity level" filter so unfinished solutions can be shown for debugging/preview

**Comment by tobka777** [comment]
To see the "Maturity level" filter you can add the GET parameter `show=maturity`

**Comment by tobka777** [comment]
If we have no entry for a filter (disabled), then the filter shouldn't be visible.
